### ISSUE TITLE
LC10

### ISSUE THREAD

**Issue by sylus28** [kloknibor/photocentric_dev#1]
Z axis don't move during the printing.
Resolution was set to 1024x600 into config file but Sliced STL was not the good measurment

**Comment by kloknibor** [comment]
Hi sylus! 

How did you install the software? I haven't tried to be honest after the last updates.

I wil try to fix it tomorrow ;)!

**Comment by sylus28** [comment]
Replace cwh entire folder by source to opt and start.sh
Try many sort of install nothing fixed

**Comment by kloknibor** [comment]
Try the image file from photonic3D.com downloads section... Also untested but I think It's more dependable.

**Comment by sylus28** [comment]
trier this image and failed

**Comment by kloknibor** [comment]
Did you add the wifi password before first boot? (In Octopi-network you set the wifi settings) or use ethernet?

**Comment by sylus28** [comment]
ethernet then wifi by command (octopi txt not works)

**Comment by kloknibor** [comment]
Alright I will look into it tomorrow

**Comment by sylus28** [comment]
nice

**Comment by kloknibor** [comment]
I suppose you added an template printer with the "create"  button because the other printers return an error 400 right? This is the problem. This software is an edited photonic3d version for photocentric, by default the eGeneric driver is loaded in this software, but for the photocentric printers there is an special driver. I can instruct you how to set this manually as temporary fix or I'll let you know when the 400 error is fixed.

This error is because normally we pull the data from Github, but the policy about this has changed and now we can't pull data from Github recently, we applied a temporary fixed but it's broken again. It will be fixed no worries!

**Comment by sylus28** [comment]
Photocentric 10 profile is automatically selected
<img width="860" alt="capture d ecran 2016-07-03 a 13 35 12" src="https://cloud.githubusercontent.com/assets/17679844/16545183/16a92a7e-4123-11e6-9fee-7ddd5984ae4a.png">

**Comment by kloknibor** [comment]
Could you press download and upload the zip here for me?

**Comment by sylus28** [comment]
[LogBundle.zip](https://github.com/kloknibor/photocentric_dev/files/345234/LogBundle.zip)

**Comment by kloknibor** [comment]
I think you added the software with the instructions from the main page. These were old and were for the main development repo from Wes. I updated the instrcutions. I think you did this because I found traced of that repo in your log files.

Altough you have loaded the correct driver to control the motor. When the hood is on the printer does it move? (You can send manual movement command by pressing the printer, select controls and there you can control the Z-axis).

Please try to use the image but before first boot edit octopi-network.txt from your SDcard to set-up an wifi connection or just skip this and use ethernet. this way you will have the most features.

Or just add it with the updated instructions. try the photocentric test printer please, if the printer is preconfigured (only possible when using windows) than delete the printer and add this test printer ;)!

**Comment by sylus28** [comment]
Software not launch when run new image
Z works in manual mode but not move in print process on

**Comment by kloknibor** [comment]
Ok hopefully last question, can you replicate the no movement during printing problem for me and send me the zip afterwards? Than I can see what is going on. The old one has been made only when turning the printer on

**Comment by kloknibor** [comment]
@sylus28 where are you located if I may ask? Maybe if we are in the same timezone I can help you better :)!

Sorry for the guessing work for now, I'm very busy these days. I will try to test the software on my machine the end of the week (might be as late as sunday) and will record my steps for photonic3D and to help you set everything up properly ;)! And hopefully to find the same difficulties as you ;)!

**Comment by sylus28** [comment]
Located in France and I am working now,will sent you file this evening out of job

**Comment by kloknibor** [comment]
Alright no problem! I'm working too ;)! I'm from the Netherlands so we are in the same timezone. If intrested we can have a skypecall/teamviewer session in the future to set things up or discuss bugs/new features :)!

**Comment by sylus28** [comment]
[LogBundle.zip](https://github.com/kloknibor/photocentric_dev/files/348375/LogBundle.zip)
no Z move while printing
manual Z lifting works during print

**Comment by kloknibor** [comment]
> Looks like we have some trouble with the printer calculators! Thanks for uploading this code it helped a lot!

So our option for now are :

1: wait till the weekend and I will properly test this and fix it
2: let me make a an untested fix which might work, maybe after discussing with the other deva.
3: write a very limited fix which should work for now but also untested.

What do you prefer?

Thanks for working with me/us! It's appreciated!

Robin

**Comment by sylus28** [comment]
No urgency option 1 is pretty good and safe

**Comment by kloknibor** [comment]
Alright I will report during the weekend :)!

**Comment by kloknibor** [comment]
I think it is best to move this conversation to https://github.com/area515/Creation-Workshop-Host/issues to keep it all centralized. Not sure what will happen with repo in the future so it is best to keep it there ;)!

I will continue to help you over there ofcourse! And most probably I will hear from the other devs I screwed the template up haha! No worries they are friendly :)!

I will move it there for you with the needed information ;)! and post the link here

**Comment by kloknibor** [comment]
https://github.com/area515/Creation-Workshop-Host/issues/237

**Comment by kloknibor** [comment]
I think I fixed it but my display is broken currently... So I can't test properly! It should move without any problems now if you use the photocentric 10" lc from my repo and I will add them to area515 and wes his repo too ;)! Better testing will be done later sorry about that! Also the image creation I couldn't solve yet... I'm on it!

**Comment by sylus28** [comment]
test in progress but after install and reboot server not start automatically  (oblige to start.sh)
[LogBundle.zip](https://github.com/kloknibor/photocentric_dev/files/356230/LogBundle.zip)
cws file not works
during print
[LogBundle (1).zip](https://github.com/kloknibor/photocentric_dev/files/356237/LogBundle.1.zip)

**Comment by kloknibor** [comment]
How did you install? In my test scenario yesterday even the image booted the XServer automatically but the resources had some trouble for some reason...

**Comment by sylus28** [comment]
script
re install image now

**Comment by sylus28** [comment]
sudo wget https://github.com/Kloknibor/photocentric_dev/raw/master/host/bin/start.sh
sudo chmod 777 start.sh
sudo ./start.sh 
again
choose LC10 driver (last profile):
Z not move Status: Failed <eval>:1:125 Expected ) but found ; var minLift = 4.5; var value = 8; if ($CURSLICE > $NumFirstLayers) { value = minLift + ((5.0/2880) \* Math.pow($buildAreaMM,1);}value ^
[LogBundle (2).zip](https://github.com/kloknibor/photocentric_dev/files/356514/LogBundle.2.zip)

Try profile test:
Z moves but to slow and not synchro with LCD (LCD shows pattern before Z return to last point+0,1mm)
Go to work now

size of an 10_10 STL measure 15_15 after print

**Comment by kloknibor** [comment]
Hmm Well I was afraid of that already... The photocentric firmware doesn't have a function to wait for the motors. I will find a way to just implement a specific interval to wait from the photonic3d side with the other devs.

**Comment by kloknibor** [comment]
Thanks for testing by the way!
